### POST server to subscribe
POST localhost:8060/api/v1/newsletter/subscribe
Content-Type: application/json

{
  "email": "kis.pista@example.gov.uk"
}

### POST unsubscribe event
POST localhost:8060/api/v1/newsletter/unsubscribe
Content-Type: application/json

{
  "email": "kis.pista@example.gov.uk"
}

### GET information about subscription
GET localhost:8060/api/v1/newsletter/01938be4-7d1c-7272-bed0-6cc130410c29

###